### ISSUE TITLE
请问能否为 ./js/snake.js 添加注释？

### ISSUE THREAD

**Issue by Nyaasu66** [793338023/game-snake#1]
开发者你好，最近看到了你的贪食蛇游戏的代码仓库。感觉你的代码对我学习js有所帮助，便开始读你的源码。看到` ./js/snake.js` 时有点看不懂，希望你能对这个文件添加一些注释，谢谢~

**Comment by 793338023** [comment]
ok,加了，其他不懂你就找API看吧

**Comment by Nyaasu66** [comment]
感谢！
